services:
  db:
    # todo add my image
    # image: postgres:12.2
    build:
        context: ./docker/postgres
        dockerfile: Dockerfile
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  node-modules:

networks:
  db:
