services:
  app:
    image: maksrafalko/nodejs2022q4-service-app
    depends_on:
      db:
        condition: service_started
    build:
      context: .
      target: dev
    restart: on-failure
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - db
    volumes:
      - ./:/usr/src/app

  db:
    image: maksrafalko/nodejs2022q4-service-db
    build:
        context: ./docker/postgres
        dockerfile: Dockerfile
    restart: on-failure
    command: [
      "postgres",
      "-c", "log_destination=csvlog",
      "-c", "logging_collector=on",
      "-c", "log_directory=pg_log"
    ]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  db:
